### PR TITLE
Add a wrapper function RunSWNE

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
Adds a wrapper function to run SWNE analysis (derive a SWNE embedding from Seurat object). For more convenient usage (mainly with default parameters) as demonstrated in vignette examples. Allows for passing pre-computed k values for performance or consistency.

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
The FindNumFactors function has also be amended for compatibility with previously expected behaviour (as described in Issue #8).

**Comment by TomKellyGenetics** [comment]
Additional handling of `dist.use` inputs and error messages has also been added (as described in Issue #9).

**Comment by yanwu2014** [comment]
Thanks! This looks really useful!

**Comment by TomKellyGenetics** [comment]
No problem, I've tweaked it mostly to work for my own pipeline but hopefully others find it beneficial too. Sorry to pester again but I've added Methods to RunSWNE (PR #10).

**Pull request merged**
